// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: string;
	CF_HOOK: string;
	GHOST_WH_SECRET: string;
	BUFFER: DurableObjectNamespace<import("./src/index").Buffer>;
}
