name = "buffer"
main = "src/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
# [vars]
# MY_VARIABLE = "production_value"
[[durable_objects.bindings]]
name = "BUFFER"
class_name = "Buffer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Buffer"]
